function [ dt ] = matUpdateTimeInterval( obj, fphys )
dt = nan;
for m = 1:obj.Nmesh
    N = obj.meshUnion(m).cell.N;
    
    dtm = mxUpdateTimeInterval1d( ...
        obj.hmin, ...
        obj.gra, ...
        N, ...
        obj.meshUnion(m).LAV, ...
        obj.meshUnion(m).EToR, ...
        fphys{m} );
    
    if ( dtm > 0 )
        dt = min(dt, dtm*obj.cfl);
    end
end
end% func