function [ frhs ] = matEvaluateStrongFormEdgeAlterRHS( obj, fluxM, fluxP )

frhs = mxEvaluateStrongFormEdgeAlterRHS( ...
    obj.mesh.cell.invM, obj.M, ...
    obj.FToE, obj.FToN1, obj.FToN2, ...
    obj.Js, obj.mesh.J, fluxM, fluxP );

end
