function [ dflux ] = surf_term( obj, f_Q )
%SURF_TERM Summary of this function goes here
%   Detailed explanation goes here

dflux = lf_flux(f_Q, ...
    obj.f_extQ, ...
    obj.mesh.nx, ...
    obj.mesh.ny, ...
    obj.mesh.eidM, ...
    obj.mesh.eidP, ...
    obj.mesh.eidtype);

end
