function [ frhs ] = matEvaluateStrongFormEdgeCentralRHS( obj, fluxM, fluxP )

frhs = mxEvaluateStrongFormEdgeCentralRHS( ...
    obj.mesh.cell.invM, obj.M, ...
    obj.FToE, obj.FToN1, obj.FToN2, ...
    obj.Js, obj.mesh.J, fluxM, fluxP );

end
