function [ frhs ] = matEvaluateStrongFromEdgeRHS( obj, fluxM, fluxS )

frhs = mxEvaluateStrongFormEdgeRHS( ...
    obj.mesh.cell.invM, obj.M, ...
    obj.FToE, obj.FToN1, ...
    obj.Js, obj.mesh.J, fluxM, fluxS );
end

