function fphys = matVertLimit( obj, fphys, fieldId )

[ fvert, fvmin, fvmax, cvar ] = matEvaluateVertAverage( obj, fphys, fieldId );

for m = 1:obj.Nmesh
    fphys{m}(:,:,fieldId) = mxVertLimit2d( fphys{m}(:,:,fieldId), ...
        obj.meshUnion(m).x, obj.meshUnion(m).y, ...
        obj.meshUnion(m).xc, obj.meshUnion(m).yc, ...
        obj.meshUnion(m).vx, obj.meshUnion(m).vy, ...
        fvert, fvmin, fvmax, cvar{m}, ...
        obj.meshUnion(m).EToV, ...
        obj.meshUnion(m).cell.Fmask);
end

end