function [ rhsQ ] = rhs_term(obj, f_Q )
%RHS_TERM Summary of this function goes here
%   Detailed explanation goes here

% [ E, G ] = flux_term(obj, f_Q); % volume flux term
% [ dflux ] = surf_term( obj, f_Q ); % surface flux deviation

% rhs = - obj.mesh.rx.*(obj.mesh.cell.Dr*E) ...
%     - obj.mesh.sx.*(obj.mesh.cell.Ds*E) ...
%     - obj.mesh.ry.*(obj.mesh.cell.Dr*G) ...
%     - obj.mesh.sy.*(obj.mesh.cell.Ds*G) ...
%     + (obj.mesh.cell.LIFT*( obj.mesh.Js.*dflux ))./obj.mesh.J;
v_Q = f_Q;
mesh = obj.mesh;
cell = mesh.cell;

[ rhsQ, rhsV ] = rhs_term(f_Q, v_Q, obj.f_extQ, obj.u, obj.v, ...
    mesh.nx, mesh.ny, mesh.eidM, mesh.eidP, mesh.eidtype, mesh.EToR, ... 
    cell.Dr, cell.Ds, mesh.rx, mesh.ry, mesh.sx, mesh.sy, ...
    cell.LIFT, mesh.J, mesh.Js);
end