function [ rhsQ ] = rhs_term(obj, f_Q )
%RHS_TERM Summary of this function goes here
%   Detailed explanation goes here

v_Q = f_Q;

[ rhsQ, rhsV ] = rhs_term(f_Q, v_Q, obj.f_extQ, obj.u, obj.v, ...
    obj.mesh.nx, obj.mesh.ny, ...
    obj.mesh.eidM, obj.mesh.eidP, obj.mesh.eidtype, obj.mesh.EToR, ... 
    obj.mesh.cell.Dr, obj.mesh.cell.Ds, ...
    obj.mesh.rx, obj.mesh.ry, obj.mesh.sx, obj.mesh.sy, ...
    obj.mesh.cell.LIFT, obj.mesh.J, obj.mesh.Js);
end