function draw(obj, varargin)
%DRAW Draw the water elevation and the flux on x and y coordinates
switch nargin
    case 1
        f_Q = obj.f_Q;
    case 2
        f_Q = varargin{1};
end
if ( isempty(obj.draw_h) || ~isvalid(obj.draw_h{1}))
    % 若图像未绘制或窗口被关闭
    EToV = ones(obj.mesh.K, 1)*obj.mesh.cell.Fmask(:)';
    EToV = EToV + ( obj.mesh.cell.Np*(0:obj.mesh.K-1) )'...
        *ones(1, obj.mesh.cell.Nfptotal);
    figure('color', 'w', 'Position', [440, 500, 720, 300]);
    axes('Position', [0.1, 0.1, 0.35, 0.75])
    % 绘制底坡
    patch('Vertices', [obj.mesh.x(:), obj.mesh.y(:), obj.bot(:)], ...
        'Faces', EToV, ...
        'FaceColor', [.8, .8, .8]);
    % 绘制水面
    f = f_Q(:,:,1); f(f<obj.hmin) = nan;
    obj.draw_h{1} = patch(...
        'Vertices', [obj.mesh.x(:), obj.mesh.y(:), f(:)+obj.bot(:)], ...
        'Faces', EToV, ...
        'EdgeColor', 'k', ...
        'FaceColor', 'interp', ...
        'FaceVertexCData', f(:), ...
        'FaceAlpha', 0.8);
    view(-28, 28); colormap(jet); box on; grid on;
%     zlim([1.5, 5]); 
    fontsize = 16;
    xlabel('$x$', 'Interpreter', 'latex', 'FontSize', fontsize);
    ylabel('$y$', 'Interpreter', 'latex', 'FontSize', fontsize);
    zlabel('$\eta$', 'Interpreter', 'latex', 'FontSize', fontsize);
    
    % 绘制流量 qx
    axes('Position', [0.55, 0.6, 0.35, 0.35])
    f = f_Q(:,:,2);
    obj.draw_h{2} = patch(...
        'Vertices', [obj.mesh.x(:), obj.mesh.y(:), f(:)], ...
        'Faces', EToV, ...
        'EdgeColor', 'k', ...
        'FaceColor', 'interp', ...
        'FaceVertexCData', f(:) );
    xlabel('$x$', 'Interpreter', 'latex', 'FontSize', fontsize);
    ylabel('$y$', 'Interpreter', 'latex', 'FontSize', fontsize);
    zlabel('$q_x$', 'Interpreter', 'latex', 'FontSize', fontsize);
    view(20, 32); colormap(jet); box on; grid on;
%     zlim([-0.02, 0.02]);
    
    % 绘制流量 qy
    axes('Position', [0.55, 0.1, 0.35, 0.35])
    f = f_Q(:,:,3);
    obj.draw_h{3} = patch(...
        'Vertices', [obj.mesh.x(:), obj.mesh.y(:), f(:)], ...
        'Faces', EToV, ...
        'EdgeColor', 'k', ...
        'FaceColor', 'interp', ...
        'FaceVertexCData', f(:) );
    xlabel('$x$', 'Interpreter', 'latex', 'FontSize', fontsize);
    ylabel('$y$', 'Interpreter', 'latex', 'FontSize', fontsize);
    zlabel('$q_y$', 'Interpreter', 'latex', 'FontSize', fontsize);
    view(20, 32); colormap(winter); box on; grid on;
%     zlim([-0.01, .01]);
else % 若图像存在
    hmin = 1e-2;
    f = f_Q(:,:,1); f( f<hmin ) = nan; % 消去干网格
    set(obj.draw_h{1}, ...
        'Vertices', [obj.mesh.x(:), obj.mesh.y(:), f(:)+obj.bot(:)],...
        'FaceVertexCData', f(:));
    f = f_Q(:,:,2);
    set(obj.draw_h{2}, ...
        'Vertices', [obj.mesh.x(:), obj.mesh.y(:), f(:)],...
        'FaceVertexCData', f(:));
    f = f_Q(:,:,3);
    set(obj.draw_h{3}, ...
        'Vertices', [obj.mesh.x(:), obj.mesh.y(:), f(:)],...
        'FaceVertexCData', f(:));
end
end

