function [ dflux ] = hll_surf_term( obj, f_Q )
%HLL_SURF_TERM Summary of this function goes here
%   Detailed explanation goes here

dflux = zeros(obj.mesh.cell.Nfptotal, obj.mesh.K, obj.Nfield);

[dflux(:,:,1), dflux(:,:,2), dflux(:,:,3)] = hll_flux(...
    obj.hmin, obj.gra, ...
    f_Q(:,:,1), f_Q(:,:,2), f_Q(:,:,3), obj.bot, ...
    obj.f_extQ(:,:,1), obj.f_extQ(:,:,2), obj.f_extQ(:,:,3), ...
    obj.mesh.nx, obj.mesh.ny, ...
    obj.mesh.eidM, obj.mesh.eidP, obj.mesh.eidtype);
end

